### ISSUE TITLE
suggest to seperate bas2Cpp and compilation 

### ISSUE THREAD

**Issue by retsyo** [kankouhin/Kaya-BASIC#1]
I test Kaya-BASIC in my msys2+mingw64 on win7

1. for most of wxGUI's demo, I use
```
cd /r/Kaya-BASIC-master/samples/wxGUI/bppgui/

../../../bin/bpp -k -w gui.bas

g++ gui.cpp -Wall ../../../lib/libSystem64.a -I../../../lib/core ../../../lib/core/core64.o ../../../lib/core/core_res64.o ../../../lib/core/stw64.o  `/mingw64/bin/wx-config --version=3.1 --static=yes --cxxflags --libs`  -static
```
which can generate `a.exe` as expected.

So I suggest `bpp` only translate the BASIC source into CPP, then `bpp` write a shell file or batch file to compile the `CPP` into executable binary. 

2. for `R:\Kaya-BASIC-master\samples\wxGUI\menu&toolbar\`, since I don't know the detailed command line to compile `toolbar.rc`, I can't make the exe file

3. for demos under `R:\Kaya-BASIC-master\samples\coretests\`
I use 
```
cd /r/Kaya-BASIC-master/samples/coretests/comole/

../../../bin/bpp -k  test.bas

g++ test.cpp -Wall ../../../lib/libSystem64.a -I../../../lib/core ../../../lib/core/core64.o ../../../lib/core/core_res64.o ../../../lib/core/stc64.o  `/mingw64/bin/wx-config --version=3.1 --static=yes --cxxflags --libs`  -static
```

The generated exe can run because Excel is lauched and the sheet is modified.

However, for other demos which use `print`, there is no output while the exe is running. So I don't know wether they run correctly.

4. the last question. Which features will be supplied by Kaya-BASIC? Can it be used as a freebasic competitor?

**Comment by kankouhin** [comment]
Thanks for your testing.
1. -p option only output the cpp file.
    shell file or batch file maybe add a option in the further.

2. you can use this to compile res file.
  `windres  -IC:\wxWidgets-3.1.3\include -J rc -O coff -i core.rc -o core_res32.o`

3. I Update all the comole samples with GUI and MsgBox. you can donwload those and compile again.

4.  FreeBasic is a gread,  profession, complex Compiler, Kaya-BASIC like a tool.
     If i have time, i should make Linux and Mac Version.
     the Biggest feature is maybe  can use all the wxWidgets Classes and Functions.

**Comment by kankouhin** [comment]
> 
> 
> I test Kaya-BASIC in my msys2+mingw64 on win7
> 
>     1. for most of wxGUI's demo, I use
> 
> 
> ```
> cd /r/Kaya-BASIC-master/samples/wxGUI/bppgui/
> 
> ../../../bin/bpp -k -w gui.bas
> 
> g++ gui.cpp -Wall ../../../lib/libSystem64.a -I../../../lib/core ../../../lib/core/core64.o ../../../lib/core/core_res64.o ../../../lib/core/stw64.o  `/mingw64/bin/wx-config --version=3.1 --static=yes --cxxflags --libs`  -static
> ```
> 
> which can generate `a.exe` as expected.
> 
> So I suggest `bpp` only translate the BASIC source into CPP, then `bpp` write a shell file or batch file to compile the `CPP` into executable binary.
> 
>     1. for `R:\Kaya-BASIC-master\samples\wxGUI\menu&toolbar\`, since I don't know the detailed command line to compile `toolbar.rc`, I can't make the exe file
> 
>     2. for demos under `R:\Kaya-BASIC-master\samples\coretests\`
>        I use
> 
> 
> ```
> cd /r/Kaya-BASIC-master/samples/coretests/comole/
> 
> ../../../bin/bpp -k  test.bas
> 
> g++ test.cpp -Wall ../../../lib/libSystem64.a -I../../../lib/core ../../../lib/core/core64.o ../../../lib/core/core_res64.o ../../../lib/core/stc64.o  `/mingw64/bin/wx-config --version=3.1 --static=yes --cxxflags --libs`  -static
> ```
> 
> The generated exe can run because Excel is lauched and the sheet is modified.
> 
> However, for other demos which use `print`, there is no output while the exe is running. So I don't know wether they run correctly.
> 
>     1. the last question. Which features will be supplied by Kaya-BASIC? Can it be used as a freebasic competitor?

**Comment by kankouhin** [comment]
You need download all the files to compile  samles
because libs and bin has changed.

**Comment by retsyo** [comment]
thank you for updating

To use all the wxWidgets Classes and Functions is a highlight. However, I do hope to do more works in one application written in only one language. So I will keep an eye on Kaya-BASIC and wait for 

1. opensourced Kaya-BASIC with more wxWidgets examples from wxBasic/wxWidgets/wxPython

2. detailed document on Kaya-BASIC itself to check whether it has rich data type and operation, necessary flow control, user-defined function/sub with default variant overloaded function

3. since I often treat text and math, I do hope some syntax sugar which I stated in https://www.freebasic.net/forum/viewtopic.php?f=17&t=28280&p=268729#p269622

4. a tool can translate C header to be used in Kaya-BASIC
