### ISSUE TITLE
bpp::string can not be used in wxWdigets

### ISSUE THREAD

**Issue by retsyo** [kankouhin/Kaya-BASIC#2]
just change r:\Kaya-BASIC-master\samples\wxGUI\treectrl\gui.bas 
from
```
f = New wxFrame( NULL, wxID_ANY, "treectrl demo" )
```

to
```
  dim strTitle as string = "treectrl demo"
  f = New wxFrame( NULL, wxID_ANY,  strTitle)
```

you will find what I am saying

**Comment by kankouhin** [comment]
because String can not convert to wxString.
please use @strTitle
`f = New wxFrame( NULL, wxID_ANY,  @strTitle)`

**Comment by kankouhin** [comment]
you can alse dim a wxString like.
`Dim strTitle as wxString = wxString("Standard Controls")`
`f = New wxFrame( NULL, wxID_ANY,  strTitle)`

**Comment by retsyo** [comment]
那和用C区别在哪？只是语法上略微变了一点。

用BASIC不就图看上去简短，写着简单，初学者也可以用。

**Comment by kankouhin** [comment]
有限制性的进行了修改，您可以重新下载再测试一下。
仅支持传递字符串变量，不支持字符串表达式或者字符串函数，如果有更多的个人时间以后会慢慢修改。
```
Dim s As String = "Hello Kaya-BASIC"
wxFrame.SetTitle( s )　　　　　　　　　　　　　OK
wxFrame.SetTitle( s + "Kaya" )　　　　　　　　 NG
WorkSheets(1).Cells(1,1) = s　　　　　　　　　 OK
WorkSheets(1).Cells(1,1) = s + "Kaya"　　　　　NG
```
